/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import clases.Gimnasio;
import controller.Controlador;

/**
 *
 * @author Alessandro
 */
public class TablaEntrenador extends javax.swing.JFrame {
    
    //Variables
    Controlador control ;
    private String cedulaEnt = "";
    private String nombreEnt = "";
    private String edadEnt = "";
    private String sexoEnt = "";
    private String pesoEnt = "";
    private String alturaEnt = "";
    private String direccionEnt = "";
    private String experienciaEnt = "";
    private String especialidadEnt = "";
    
    /**
     * Creates new form TablaEntrenador
     */
    //Contructores
    public TablaEntrenador() {
        initComponents();
        control = new Controlador(this);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    public TablaEntrenador(Gimnasio gym, String tipoBoton) {
        initComponents();
        control = new Controlador(this);
        control.llenarTablaEnt(tablaEntrenador);

        if (tipoBoton.equals("Eliminar")) {

            btnEliminarEnt.setVisible(true);
            btnModificarEnt.setVisible(false);

        } else if (tipoBoton.equals("Modificar")) {

            btnEliminarEnt.setVisible(false);
            btnModificarEnt.setVisible(true);

        } else if (tipoBoton.equals("")) {

            btnEliminarEnt.setVisible(false);
            btnModificarEnt.setVisible(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEntrenador = new javax.swing.JTable();
        btnAtras = new javax.swing.JButton();
        btnEliminarEnt = new javax.swing.JToggleButton();
        btnModificarEnt = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaEntrenador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Cédula", "Edad", "Sexo", "Dirección", "Peso", "Altura", "Experiencia", "Especialidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaEntrenador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEntrenadorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEntrenador);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1040, 200));

        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 230, -1, -1));

        btnEliminarEnt.setText("Eliminar Entrenador");
        getContentPane().add(btnEliminarEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 150, -1));

        btnModificarEnt.setText("Modificar Entrenador");
        getContentPane().add(btnModificarEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaEntrenadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEntrenadorMouseClicked
        // TODO add your handling code here:
        int i = tablaEntrenador.getSelectedRow();
        nombreEnt = (tablaEntrenador.getValueAt(i, 0).toString());
        cedulaEnt = (tablaEntrenador.getValueAt(i, 1).toString());
        edadEnt = (tablaEntrenador.getValueAt(i, 2).toString());
        sexoEnt = (tablaEntrenador.getValueAt(i, 3).toString());
        direccionEnt = (tablaEntrenador.getValueAt(i, 4).toString());
        pesoEnt = (tablaEntrenador.getValueAt(i, 5).toString());
        alturaEnt = (tablaEntrenador.getValueAt(i, 6).toString());
        experienciaEnt = (tablaEntrenador.getValueAt(i, 6).toString());
        especialidadEnt = (tablaEntrenador.getValueAt(i, 6).toString());
    }//GEN-LAST:event_tablaEntrenadorMouseClicked

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        VentanaGimnasio ventana = new VentanaGimnasio();
        control.activaVentana(ventana, this);
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaEntrenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaEntrenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaEntrenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaEntrenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaEntrenador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JToggleButton btnEliminarEnt;
    private javax.swing.JToggleButton btnModificarEnt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEntrenador;
    // End of variables declaration//GEN-END:variables
}
