/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import clases.Deportista;
import clases.Gimnasio;
import controller.Controlador;
import javax.swing.JToggleButton;

/**
 *
 * @author Alessandro
 */
public class VentanaGimnasio extends javax.swing.JFrame {
    //Gimnasio gym = new Gimnasio() ;
    Gimnasio  gym = new  Gimnasio();
    TablaDeportista tablaDepo;
    Deportista depoActual;
    Controlador control;
    
    
    /**
     * Creates new form VentanaGimnasio
     */
    public VentanaGimnasio() {
        initComponents();
        control = new Controlador(this);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtras = new javax.swing.JButton();
        btnModificarDepo = new javax.swing.JToggleButton();
        btnEliminarDepo = new javax.swing.JToggleButton();
        btnMostrarDepo = new javax.swing.JToggleButton();
        btnEliminarEnt = new javax.swing.JToggleButton();
        btnModificarEnt = new javax.swing.JToggleButton();
        btnMostrarEnt = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gimnasio");

        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnModificarDepo.setText("Modificar Datos");
        btnModificarDepo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarDepoActionPerformed(evt);
            }
        });

        btnEliminarDepo.setText("Eliminar Datos");
        btnEliminarDepo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDepoActionPerformed(evt);
            }
        });

        btnMostrarDepo.setText("Mostrar Datos");
        btnMostrarDepo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarDepoActionPerformed(evt);
            }
        });

        btnEliminarEnt.setText("Eliminar Datos");
        btnEliminarEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEntActionPerformed(evt);
            }
        });

        btnModificarEnt.setText("Modificar Datos");
        btnModificarEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarEntActionPerformed(evt);
            }
        });

        btnMostrarEnt.setText("Mostrar Datos");
        btnMostrarEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarEntActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAtras))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEliminarDepo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(btnEliminarEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnModificarDepo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModificarEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMostrarDepo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMostrarEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarDepo)
                    .addComponent(btnEliminarEnt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificarDepo)
                    .addComponent(btnModificarEnt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarDepo)
                    .addComponent(btnMostrarEnt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnAtras)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        VentanaMenu ventana = new VentanaMenu();
        control.activaVentana(ventana, this);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnModificarDepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarDepoActionPerformed
        // TODO add your handling code here:
        TablaDeportista tabla = new TablaDeportista(gym,"Modificar");
        control.activaVentana(tabla,this); 
    }//GEN-LAST:event_btnModificarDepoActionPerformed

    private void btnModificarEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarEntActionPerformed
        // TODO add your handling code here:
        TablaEntrenador tabla = new TablaEntrenador(gym,"Modificar");
        control.activaVentana(tabla,this); 
    }//GEN-LAST:event_btnModificarEntActionPerformed

    private void btnMostrarDepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarDepoActionPerformed
        // TODO add your handling code here:
        
        TablaDeportista tabla = new TablaDeportista(gym,"");
        control.activaVentana(tabla,this); 
    }//GEN-LAST:event_btnMostrarDepoActionPerformed

    private void btnEliminarDepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDepoActionPerformed
        // TODO add your handling code here:
        TablaDeportista tabla = new TablaDeportista(gym,"Eliminar");
        control.activaVentana(tabla,this); 
   
    }//GEN-LAST:event_btnEliminarDepoActionPerformed

    private void btnEliminarEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEntActionPerformed
        // TODO add your handling code here:
        TablaEntrenador tabla = new TablaEntrenador(gym,"Eliminar");
        control.activaVentana(tabla,this); 
    }//GEN-LAST:event_btnEliminarEntActionPerformed

    private void btnMostrarEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarEntActionPerformed
        // TODO add your handling code here:
        TablaEntrenador tabla = new TablaEntrenador(gym,"");
        control.activaVentana(tabla,this); 
    }//GEN-LAST:event_btnMostrarEntActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGimnasio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGimnasio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGimnasio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGimnasio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaGimnasio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JToggleButton btnEliminarDepo;
    private javax.swing.JToggleButton btnEliminarEnt;
    private javax.swing.JToggleButton btnModificarDepo;
    private javax.swing.JToggleButton btnModificarEnt;
    private javax.swing.JToggleButton btnMostrarDepo;
    private javax.swing.JToggleButton btnMostrarEnt;
    // End of variables declaration//GEN-END:variables
}
