/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.Deportista;
import modelo.Gimnasio;
import com.placeholder.PlaceHolder;
import com.sun.awt.AWTUtilities;
import controller.Controlador;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import persistencia.PersonasXml;

/**
 *
 * @author Alessandro
 */
public class VentanaDeportista extends javax.swing.JFrame {

    Controlador control = new Controlador(this);
    Deportista dep = new Deportista();
    Gimnasio gym = new Gimnasio();
    PersonasXml datosDep = new PersonasXml();
    private boolean resultado = false;
    PlaceHolder holder;

    /**
     * Creates new form VentanaDeportista
     */
    public VentanaDeportista() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        btnRegistrarModificacion.setVisible(false);
        control = new Controlador(this);
        holder = new PlaceHolder(txtCedula, " [min:7 digitos - max:9 digitos] ");
        holder = new PlaceHolder(txtConfirmar, " Confirme su Cédula ");
        holder = new PlaceHolder(txtFrecuenciaCardiaca, " [min:60 (LPM) - max:1000 (LPM)] ");
        holder = new PlaceHolder(txtEdad, " [min:18 años - max:100 años] ");
        holder = new PlaceHolder(txtPeso, " [min:45 Kg - max:500 Kg] ");
        holder = new PlaceHolder(txtAltura, " [min:1.45 m - max:2.7 m] ");
        holder = new PlaceHolder(txtNombre, " Ej: Antonio Perez Gonzalez");
        holder = new PlaceHolder(txtDireccion, " Ej: Av.Teheran , Montalban II , Caracas , Venezuela");
    }

    public void modificacionDepo(Deportista dep) {
        String numDouble;

        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        txtCedula.enable(false);
        txtConfirmar.enable(false);
        btnRegistrar.setVisible(false);
        btnRegistrarModificacion.setVisible(true);
        control = new Controlador(this);
        this.txtAltura.setText(numDouble = Double.toString(dep.getAltura()));
        this.txtCedula.setText(numDouble = Integer.toString(dep.getCedula()));
        this.txtDireccion.setText(dep.getDireccion());
        this.txtEdad.setText(numDouble = Integer.toString(dep.getEdad()));
        this.txtFrecuenciaCardiaca.setText(numDouble = Integer.toString(dep.getRitmoCardiaco()));
        this.txtNombre.setText(dep.getNombre());
        this.txtPeso.setText(numDouble = Double.toString(dep.getPeso()));

    }

    public void InicializarCamposDepo() {
        this.txtCedula.setText(null);
        this.txtNombre.setText("");
        this.txtEdad.setText("");
        this.txtPeso.setText("");
        this.txtAltura.setText("");
        this.txtDireccion.setText("");
        this.txtFrecuenciaCardiaca.setText("");
        this.txtConfirmar.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        comboSexo = new javax.swing.JComboBox<>();
        txtPeso = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDireccion = new javax.swing.JTextArea();
        txtFrecuenciaCardiaca = new javax.swing.JTextField();
        comboFrecuenciaEntrenamiento = new javax.swing.JComboBox<>();
        comboTipoEjercicio = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JToggleButton();
        btnAtras = new javax.swing.JButton();
        btnRegistrarModificacion = new javax.swing.JButton();
        txtConfirmar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Datos");
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Tipo de ejercicio");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 260, 30));

        jLabel10.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Nombre y Apellido");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 200, 30));

        jLabel11.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Cédula Identidad");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 200, 30));

        jLabel12.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Edad");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 200, 30));

        jLabel13.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Sexo");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 200, 30));

        jLabel14.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Peso ");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 200, 30));

        jLabel15.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Altura");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 200, 30));

        jLabel16.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Dirección");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 200, 30));

        jLabel17.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Frecuencia Cardíaca");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 220, 30));

        jLabel18.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Frecuencia de Entrenamiento");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 260, 30));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 390, -1));

        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });
        jPanel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 180, -1));

        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadKeyTyped(evt);
            }
        });
        jPanel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 180, -1));

        comboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        jPanel1.add(comboSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 180, -1));

        txtPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPesoKeyTyped(evt);
            }
        });
        jPanel1.add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 390, -1));

        txtAltura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAlturaKeyTyped(evt);
            }
        });
        jPanel1.add(txtAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 390, -1));

        txtDireccion.setColumns(20);
        txtDireccion.setRows(5);
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtDireccion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 390, 60));
        jScrollPane1.getAccessibleContext().setAccessibleName("");
        jScrollPane1.getAccessibleContext().setAccessibleDescription("");

        txtFrecuenciaCardiaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFrecuenciaCardiacaKeyTyped(evt);
            }
        });
        jPanel1.add(txtFrecuenciaCardiaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 390, -1));

        comboFrecuenciaEntrenamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diario", "Semanal" }));
        jPanel1.add(comboFrecuenciaEntrenamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 180, -1));

        comboTipoEjercicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tonificacion", "reduccion de peso", "reduccion de medidas", "cardio", "pesas", "flexibilidad y equilibrio", "relajacion" }));
        jPanel1.add(comboTipoEjercicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 390, -1));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de datos del deportista ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 390, 50));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));
        btnRegistrar.getAccessibleContext().setAccessibleDescription("");

        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 520, -1, -1));

        btnRegistrarModificacion.setText("Guardar Cambios");
        btnRegistrarModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarModificacionActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarModificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        txtConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(txtConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 180, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IconoDeportista.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 50, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo4.jpeg"))); // NOI18N
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        VentanaMenu ventana = new VentanaMenu();
        control.activaVentana(ventana, this);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:

        if (txtNombre.getText().isEmpty() || txtCedula.getText().isEmpty() || txtAltura.getText().isEmpty() || txtDireccion.getText().isEmpty() || txtEdad.getText().isEmpty() || txtFrecuenciaCardiaca.getText().isEmpty() || txtPeso.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Es obligatorio llenar todos los campos");
        } else {
            if (txtCedula.getText().length() < 7) {
                JOptionPane.showMessageDialog(null, "La cedula debe tener minimo 7 digitos");
            } else {
                if ((Integer.parseInt(txtFrecuenciaCardiaca.getText()) < 50) || (Integer.parseInt(txtFrecuenciaCardiaca.getText()) > 1000)) {
                    JOptionPane.showMessageDialog(null, "La Frecuencia Cardiaca debe ser entre 50 y 1000 LPM");
                } else {
                    if ((Integer.parseInt(txtEdad.getText()) < 18) || (Integer.parseInt(txtEdad.getText()) > 100)) {
                        JOptionPane.showMessageDialog(null, "La edad debe ser entre 18 y 100 años");
                    } else {
                        if ((Integer.parseInt(txtPeso.getText()) < 45) || (Integer.parseInt(txtPeso.getText()) > 500)) {
                            JOptionPane.showMessageDialog(null, "El peso debe ser entre 45 y 500 kg");
                        } else {
                            if ((Double.parseDouble(txtAltura.getText()) < 1.45) || (Double.parseDouble(txtAltura.getText()) > 2.70)) {
                                JOptionPane.showMessageDialog(null, "La altura debe ser entre 1.45 y 2.70 m");
                            } else {
                                Deportista dep = datosDep.buscarDeportista(Integer.parseInt(txtCedula.getText()));
                                if (dep != null) {

                                    JOptionPane.showMessageDialog(null, "Estudiante ya está registrado ", "Error al Registrar", JOptionPane.ERROR_MESSAGE);

                                } else {
                                    if (txtCedula.getText().equals(txtConfirmar.getText())) {
                                        Deportista depo = new Deportista(Integer.parseInt(txtCedula.getText()), txtNombre.getText(), Integer.parseInt(txtEdad.getText()), (String) comboSexo.getSelectedItem(), Double.parseDouble(txtPeso.getText()), Double.parseDouble(txtAltura.getText()), txtDireccion.getText(), Integer.parseInt(txtFrecuenciaCardiaca.getText()), (String) comboFrecuenciaEntrenamiento.getSelectedItem(), (String) comboTipoEjercicio.getSelectedItem());
                                        //pantalla y los asociamos al objeto persona
                                        control.datosDeportista(txtCedula, txtNombre, txtEdad, txtPeso, txtAltura, txtDireccion, txtFrecuenciaCardiaca, comboSexo, comboTipoEjercicio, comboFrecuenciaEntrenamiento); //capturamos los datos indicados desde la 
                                        resultado = datosDep.agregarDeportista(depo);
                                        if (resultado == true) {
                                            InicializarCamposDepo(); //blanqueamos botones
                                            JOptionPane.showMessageDialog(null, "Registrado exitosamente!!!");
                                        }
                                    } else {
                                        JOptionPane.showMessageDialog(null, "Error con el campo Cédula", "ERROR", JOptionPane.WARNING_MESSAGE);

                                    }
                                }
                            }

                        }

                    }

                }

            }

        }

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnRegistrarModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarModificacionActionPerformed
        // TODO add your handling code here:
        String tipoUso = "Modificar";

        if (txtNombre.getText().isEmpty() || txtCedula.getText().isEmpty() || txtAltura.getText().isEmpty() || txtDireccion.getText().isEmpty() || txtEdad.getText().isEmpty() || txtFrecuenciaCardiaca.getText().isEmpty() || txtPeso.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Es obligatorio llenar todos los campos");
        } else {
            if (txtCedula.getText().length() < 7) {
                JOptionPane.showMessageDialog(null, "La cedula debe tener minimo 7 digitos");
            } else {
                if ((Integer.parseInt(txtFrecuenciaCardiaca.getText()) < 50) || (Integer.parseInt(txtFrecuenciaCardiaca.getText()) > 1000)) {
                    JOptionPane.showMessageDialog(null, "La Frecuencia Cardiaca debe ser entre 50 y 1000 LPM");
                } else {
                    if ((Integer.parseInt(txtEdad.getText()) < 18) || (Integer.parseInt(txtEdad.getText()) > 100)) {
                        JOptionPane.showMessageDialog(null, "La edad debe ser entre 18 y 100 años");
                    } else {
                        if ((Double.parseDouble(txtPeso.getText()) < 45) || (Double.parseDouble(txtPeso.getText()) > 500)) {
                            JOptionPane.showMessageDialog(null, "El peso debe ser entre 45 y 500 kg");
                        } else {
                            if ((Double.parseDouble(txtAltura.getText()) < 1.45) || (Double.parseDouble(txtAltura.getText()) > 2.70)) {
                                JOptionPane.showMessageDialog(null, "La altura debe ser entre 1.45 y 2.70 m");
                            } else {
                                control.datosDeportistaMod(dep, txtCedula, txtNombre, txtEdad, txtPeso, txtAltura, txtDireccion, txtFrecuenciaCardiaca, comboSexo, comboTipoEjercicio, comboFrecuenciaEntrenamiento); //capturamos los datos indicados desde la 
                                //pantalla y los asociamos al objeto persona
                                InicializarCamposDepo(); //blanqueamos botones
                                JOptionPane.showMessageDialog(null, "Cambios registrados exitosamente!!!");

                            }

                        }

                    }

                }

            }

        }

        TablaDeportista tabla = new TablaDeportista(tipoUso);
        control.activaVentana(tabla, this);
    }//GEN-LAST:event_btnRegistrarModificacionActionPerformed

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
        // TODO add your handling code here:
        String s1 = String.valueOf(evt.getKeyChar());

        if (!(s1.matches("^[a-zA-Z0-9.# ]*$"))) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtDireccionKeyTyped

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        // TODO add your handling code here:
        String s1 = String.valueOf(evt.getKeyChar());
        if (!(s1.matches("^[0-9]$")) || txtCedula.getText().length() > 7) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        String s1 = String.valueOf(evt.getKeyChar());

        if (!(s1.matches("^[a-zA-Z ]*$")) || txtNombre.getText().length() > 30) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtFrecuenciaCardiacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFrecuenciaCardiacaKeyTyped
        // TODO add your handling code here:
        String s1 = String.valueOf(evt.getKeyChar());

        if (!(s1.matches("^[0-9]$")) || txtFrecuenciaCardiaca.getText().length() > 3) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtFrecuenciaCardiacaKeyTyped

    private void txtEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyTyped
        // TODO add your handling code here:
        String s1 = String.valueOf(evt.getKeyChar());

        if (!(s1.matches("^[0-9]$")) || txtEdad.getText().length() > 2) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtEdadKeyTyped

    private void txtPesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesoKeyTyped
        // TODO add your handling code here:
        String s1 = String.valueOf(evt.getKeyChar());

        if (!(s1.matches("^[0-9]$")) || txtPeso.getText().length() > 2) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtPesoKeyTyped

    private void txtAlturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlturaKeyTyped
        // TODO add your handling code here:
        String s1 = String.valueOf(evt.getKeyChar());

        if (!(s1.matches("^[0-9.]$")) || txtAltura.getText().length() > 3) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtAlturaKeyTyped

    private void txtConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDeportista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDeportista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDeportista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDeportista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDeportista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JToggleButton btnRegistrar;
    private javax.swing.JButton btnRegistrarModificacion;
    private javax.swing.JComboBox<String> comboFrecuenciaEntrenamiento;
    private javax.swing.JComboBox<String> comboSexo;
    private javax.swing.JComboBox<String> comboTipoEjercicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtConfirmar;
    private javax.swing.JTextArea txtDireccion;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtFrecuenciaCardiaca;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables

}
